### ISSUE TITLE
Color name conflict with existing colors

### ISSUE THREAD

**Issue by morganestes** [AaronRutley/valetpress#1]
When I run a command like `vp help`, my shell complains about certain colors already declared as readonly, and the color output doesn't get set. Instead I get

```
ValetPress Commands:\033[00m
\033[1m vp empty\033[00m  to create a empty WP site with the 2016 theme
\033[1m vp create\033[00m to create a WP site from your starter git repo
\033[1m vp clone\033[00m  to create a WP site from an existing git repo
\033[1m vp start\033[00m  to start working on an existing project / theme
\033[1m vp delete\033[00m to delete an existing WP project
```

Part of this is my fault, as I have unprefixed color global constants in another file, but could be alleviated by setting the colors within the `_vp` function scope.

**Comment by AaronRutley** [comment]
@morganestes thanks for reporting this, I'll push up a fix for this now!
